#!/usr/bin/bash

print_help() {
	echo "Downloads files from a list of URLs nicely."
	echo "Usage: $0 URLFile OutputDirectory/ [-w wait_time]"
	echo ""
	echo "-w: wait time in seconds on average. Default 5."
	exit 1
}

if [[ $# -lt 2 ]]; then
	print_help
	exit 1
fi

SHUFFLED=`mktemp`
FILE=$1
DIR=$2
WAIT_TIME=5  # seconds

OPTIND=3
while getopts 'w:' OPTION; do
case $OPTION in
	w) WAIT_TIME=$OPTARG ;;
	?) print_help; exit 1 ;;
esac
done

# Download files in random order
shuf -o $SHUFFLED $FILE

# Make sure output directory exists
mkdir -p $DIR

USER_AGENT='Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0'

# Do the download
wget -i $SHUFFLED -w $WAIT_TIME --random-wait -P $DIR --user-agent="$USER_AGENT"

rm $SHUFFLED
